import MainWrapper from "@/layouts/main/MainWrapper"
import Sidebar from "@/layouts/sidebar/Sidebar"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "./Providers"
import "./globals.css"
import styles from "./layout.module.scss"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "DexHelper",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={cn(styles.body, inter.className, "dark")} >
          <div className={styles.wrapper}>
            <Sidebar />
            <MainWrapper>
              {children}
            </MainWrapper>
          </div>
        </body>
      </Providers>
    </html>
  );
}
