import Sidebar from "@/layouts/sidebar/Sidebar"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import styles from "./layout.module.scss"
import Providers from "./providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "DexHelper",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={cn(styles.body, inter.className)}>
          <Sidebar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
